### ISSUE TITLE
Update readme with v6.0.0 migration guide

### ISSUE THREAD

**Issue by lavigne958** [burnash/gspread#1279]
## Overview
Update the main readme with a new temporary section with guidelines for migrating to v6.0.0

**Comment by alifeee** [comment]
breaking changes:

- [ ] client -> http client #1190
- [ ] no Python 3.7 support #1234
- [ ] colors: dict -> hex #1270
- [ ] update: function args swapped #1254

**Comment by alifeee** [comment]
we should also

- [ ] make sure all of these have deprecation warnings in v5

(should we?)

**Comment by lavigne958** [comment]
sure that's a good one once we add the documentation.

I started working on the first half of the documentation.

I'll open a pr now.

**Comment by alifeee** [comment]
I have ticked the boxes above that we have implemented into the guide. For the others, I have comments:

> 1 client -> http client https://github.com/burnash/gspread/pull/1190

I don't think this is needed in a migration guide. It is not a change, but an addition.

i.e., in v5 people created a client with `service_account`. In v6, they can create one and *also* specify an HTTP client.

> 2 refresh_last_update_time: added a new function https://github.com/burnash/gspread/pull/1255

Again, I don't think this is needed, as it is an *addition*. Additions can be viewed in the Release notes. Migration guide is only for breaking changes.

> 3 sort method change: in https://github.com/burnash/gspread/pull/1254

I don't know what this means

> 4 make sure Drive API is enabled/how to enable Drive API for client secret https://github.com/burnash/gspread/issues/1292

We went back on forcing the Drive API on people #1291. Thus, they no longer *need* to enable it.

> 5 Set maintain_size to True by default https://github.com/burnash/gspread/issues/1306

This is not yet implemented

**Comment by alifeee** [comment]
With #1333, there is a deprecation warning for each tick in the above list.

Now, we should ensure there is a deprecation warning in place before ticking an above item.

**Comment by lavigne958** [comment]
> I have ticked the boxes above that we have implemented into the guide. For the others, I have comments:
> 
> > 1 client -> http client #1190
> 
> I don't think this is needed in a migration guide. It is not a change, but an addition.
> 
> i.e., in v5 people created a client with `service_account`. In v6, they can create one and _also_ specify an HTTP client.
> 
> > 2 refresh_last_update_time: added a new function #1255
> 
> Again, I don't think this is needed, as it is an _addition_. Additions can be viewed in the Release notes. Migration guide is only for breaking changes.
> 
> > 3 sort method change: in #1254
> 
> I don't know what this means

We have an open issue about rewriting the sort method signature, to better type the arguments. #1090 but I think we can't do much about it. 

> 
> > 4 make sure Drive API is enabled/how to enable Drive API for client secret #1292
> 
> We went back on forcing the Drive API on people #1291. Thus, they no longer _need_ to enable it.
> 
> > 5 Set maintain_size to True by default #1306
> 
> This is not yet implemented

**Comment by lavigne958** [comment]
last fix to apply on release_6_0_ is the sort method signature change with the helper in the README.

**Comment by lavigne958** [comment]
after this we should close this issue everything will be done.
